options:
  embed_files: true

sources:
  - type: Enterprise
    id: 5
    associations:
      - boxes
        - blocks
      - orders
      - articles
      - products:
        - images
        - product_category

# replace attributes' value (oldid: newid and other: id) and set parent association
targets:
  ProductCategory:
    8: 16268
    18: 3443
    15: 4136
    9: 1746
    22: 3821
    10: 4230
    1: 16254
    14: 3594
    17: 3534
    2: 16259
    12: 3521
    11: 87
    other: 16281
  Enterprise:
    environment_id:
      1: 2
    identifier:
      redemoinho: rede-moinho2
    theme:
      rede-moinho2: rede-moinho
  Article:
    last_changed_by_id:
      other: 87
    belongs_to: profile
  Product:
    belongs_to: profile
  Image:
    parent_id:
      other: ---
  ShoppingCartPlugin::PurchaseOrder:
    belongs_to: seller
    customer_id:
      other: ---

models_options:
  Article:
    #save_without_callbacks: true

# before save, find records using the old id and put them on the specified association
renews:
  Article:
    parent_id: 
      association: parent
      base_type: Article
#  Profile:
#    home_page_id: 
#      association: home_page
#      base_type: Article
  Product:
    product_category_id:
      association: product_category
      base_type: Category



